### ISSUE TITLE
Otologic and otolaryngological are separate in ICD-9 but otolaryngological not counted in ICD-10

### ISSUE THREAD

**Issue by caleb-easterly** [kpwhri/pmca#1]
I'm working on a project with 2016-2019 claims that only use ICD-10 codes and am using PCMA 3.2 to identify children with complex chronic disease. I've noticed that nobody is classified as having a condition affecting the otolaryngological body system (but otologic conditions have positive prevalence).

Looking at the code, it is not clear why otol/otolar are considered separately, and there appear to be inconsistencies between ICD-9 and ICD-10.

https://github.com/kpwhri/pmca/blob/d8c8ae7e0a0cf794392878046f53c0c13d793186/pmca.sas#L178-L179

In ICD-9, the following codes are `otol`: 
https://github.com/kpwhri/pmca/blob/d8c8ae7e0a0cf794392878046f53c0c13d793186/pmca.sas#L349-L350

and these are `otolar`:
https://github.com/kpwhri/pmca/blob/d8c8ae7e0a0cf794392878046f53c0c13d793186/pmca.sas#L469

In ICD-10, the following are `otol`:
https://github.com/kpwhri/pmca/blob/d8c8ae7e0a0cf794392878046f53c0c13d793186/pmca.sas#L550
https://github.com/kpwhri/pmca/blob/d8c8ae7e0a0cf794392878046f53c0c13d793186/pmca.sas#L707-L711
https://github.com/kpwhri/pmca/blob/d8c8ae7e0a0cf794392878046f53c0c13d793186/pmca.sas#L818-L819

and there are no codes assigned to `otolar`. 

Is it possible that otolaryngological conditions are left out of ICD-10 in the PMCA code? 

Or, is the inconsistency just due to inconsistency between ICD-9 and ICD-10, and nothing to be concerned about?

Thank you!

**Comment by caleb-easterly** [comment]
Any thoughts @kaiser-roy? After checking a few of the `otolar` ICD-9 codes, it seems like they are all in `otol` in ICD-10. So I may just use `otol` and forget about `otolar`.

**Comment by kaiser-roy** [comment]
hmm--that does look a bit wacky. Lemme confer w/Dr. M-S & see what she has to say. It's possible it's dropped on purpose...

**Comment by kaiser-roy** [comment]
Ach, we discussed this just last month in the context of a similar bug report & Dr M-S said:

> You are correct – we retired the term otolaryngological when we moved to ICD10 and instead used otologic for this body system.  They reference the same body system.

So I think your instinct to ignore `otolar` and just use `otol` is right on.

You buy that?

**Comment by caleb-easterly** [comment]
Yes, sounds good, thanks! If you can document it somewhere (header of the pmca.sas file?) that would help clarify for others.
